/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface ClinicInfo {
  'hours' : string,
  'name' : string,
  'address' : string,
  'phone' : string,
  'doctorName' : string,
}
export interface Review {
  'reviewerName' : string,
  'comment' : string,
  'rating' : number,
}
export interface Service { 'name' : string, 'description' : string }
export interface _SERVICE {
  'addReview' : ActorMethod<[string, Review], undefined>,
  'addService' : ActorMethod<[Service], undefined>,
  'getClinicInfo' : ActorMethod<[], ClinicInfo>,
  'getReviews' : ActorMethod<[], Array<Review>>,
  'getReviewsByRating' : ActorMethod<[], Array<Review>>,
  'getServices' : ActorMethod<[], Array<Service>>,
  'removeReview' : ActorMethod<[string], undefined>,
  'removeService' : ActorMethod<[string], undefined>,
  'updateClinicInfo' : ActorMethod<[ClinicInfo], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];