/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Review = IDL.Record({
  'reviewerName' : IDL.Text,
  'comment' : IDL.Text,
  'rating' : IDL.Nat8,
});
export const Service = IDL.Record({
  'name' : IDL.Text,
  'description' : IDL.Text,
});
export const ClinicInfo = IDL.Record({
  'hours' : IDL.Text,
  'name' : IDL.Text,
  'address' : IDL.Text,
  'phone' : IDL.Text,
  'doctorName' : IDL.Text,
});

export const idlService = IDL.Service({
  'addReview' : IDL.Func([IDL.Text, Review], [], []),
  'addService' : IDL.Func([Service], [], []),
  'getClinicInfo' : IDL.Func([], [ClinicInfo], ['query']),
  'getReviews' : IDL.Func([], [IDL.Vec(Review)], ['query']),
  'getReviewsByRating' : IDL.Func([], [IDL.Vec(Review)], ['query']),
  'getServices' : IDL.Func([], [IDL.Vec(Service)], ['query']),
  'removeReview' : IDL.Func([IDL.Text], [], []),
  'removeService' : IDL.Func([IDL.Text], [], []),
  'updateClinicInfo' : IDL.Func([ClinicInfo], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Review = IDL.Record({
    'reviewerName' : IDL.Text,
    'comment' : IDL.Text,
    'rating' : IDL.Nat8,
  });
  const Service = IDL.Record({ 'name' : IDL.Text, 'description' : IDL.Text });
  const ClinicInfo = IDL.Record({
    'hours' : IDL.Text,
    'name' : IDL.Text,
    'address' : IDL.Text,
    'phone' : IDL.Text,
    'doctorName' : IDL.Text,
  });
  
  return IDL.Service({
    'addReview' : IDL.Func([IDL.Text, Review], [], []),
    'addService' : IDL.Func([Service], [], []),
    'getClinicInfo' : IDL.Func([], [ClinicInfo], ['query']),
    'getReviews' : IDL.Func([], [IDL.Vec(Review)], ['query']),
    'getReviewsByRating' : IDL.Func([], [IDL.Vec(Review)], ['query']),
    'getServices' : IDL.Func([], [IDL.Vec(Service)], ['query']),
    'removeReview' : IDL.Func([IDL.Text], [], []),
    'removeService' : IDL.Func([IDL.Text], [], []),
    'updateClinicInfo' : IDL.Func([ClinicInfo], [], []),
  });
};

export const init = ({ IDL }) => { return []; };